version: "2.4"

networks:
  bankchain-net:

services:

  ca_peerbanka:
    image: hyperledger/fabric-ca:1.5.10
    container_name: ca_peerbanka
    restart: unless-stopped
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_peerbanka
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_TLS_ENABLED=false      # dev: tắt TLS cho CA
      # - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054  # tùy chọn
    command: sh -c "fabric-ca-server start -b admin:adminpw -d"
    volumes:
      - ca-banka-data:/etc/hyperledger/fabric-ca-server
    ports:
      - "7054:7054"
    networks:
      - bankchain-net

  ca_peerbankb:
    image: hyperledger/fabric-ca:1.5.10
    container_name: ca_peerbankb
    restart: unless-stopped
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_peerbankb
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
    command: sh -c "fabric-ca-server start -b admin:adminpw -d"
    volumes:
      - ca-bankb-data:/etc/hyperledger/fabric-ca-server
    ports:
      - "8054:8054"
    networks:
      - bankchain-net

volumes:
  ca-banka-data:
  ca-bankb-data:

